package com.genome.parpalak.dao.dao.impl.queries;

public interface ParticipantDaoQuery {
    
    String MERGE_PARTICIPANT_OBJECT = "INSERT INTO PARTICIPANT(NAME, EMAIL, USERNAME, PASSWORD) "
            + "VALUE(?,?,?,?)";
    
    String DELETE_PARTICIPANT = "DELETE FROM PARTICIPANT WHERE PARTICIPANT_ID = ?";
    
    String FIND_PARTICIPANT_BY_ID = "SELECT PARTICIPANT_ID, NAME, EMAIL, USERNAME, PASSWORD "
            + "FROM PARTICIPANT "
            + "WHERE PARTICIPANT_ID = ?";
    
    String FIND_ALL_PARTICIPANTS = "SELECT PARTICIPANT_ID, NAME, EMAIL, USERNAME, PASSWORD FROM PARTICIPANT";
    
    String MERGE_NEW_PARTICIPANT_TO_PROJECT = "INSERT INTO PROJECT_PARTICIPANT(PROJECT_ID, PARTICIPANT_ID) "
                + "VALUES(?, (SELECT PARTICIPANT_ID "
                + "FROM PARTICIPANT "
                + "WHERE EMAIL = ?))";
    
    String DELETE_PARTICIPANT_FROM_PROJECT = "DELETE FROM PROJECT_PARTICIPANT "
                + "WHERE PARTICIPANT_ID = ? "
                + "AND PROJECT_ID = ?";
    
    String FIND_PARTICIPANT_BY_USERNAME = "SELECT PARTICIPANT_ID, NAME, EMAIL, USERNAME, PASSWORD "
                + "FROM PARTICIPANT "
                + "WHERE USERNAME = ?";
    
    String FIND_PARTICIPANTS_BY_PROJECT = "SELECT PART.PARTICIPANT_ID, PART.NAME, PART.EMAIL, PART.USERNAME, PART.PASSWORD "
                + "FROM PARTICIPANT PART, PROJECT_PARTICIPANT PROJ_PART "
                + "WHERE PART.PARTICIPANT_ID = PROJ_PART.PARTICIPANT_ID "
                + "AND PROJ_PART.PROJECT_ID = ?";
    
    String DELETE_PARTICIPANT_FROM_STORY = "UPDATE TASK SET PARTICIPANT_ID = NULL "
                + "WHERE TASK_ID = ?";
    
    String MERGE_PARTICIPANT_TO_STORY = "UPDATE TASK SET PARTICIPANT_ID = ? "
                + "WHERE TASK_ID = ?";
    
    String FIND_ALL_USERNAMES = "SELECT USERNAME FROM PARTICIPANT";
    
    String FIND_ALL_EMAILES = "SELECT EMAIL FROM PARTICIPANT";
    
}
